//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoSendWeb.Models.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcoSendEntities : DbContext
    {
        public EcoSendEntities()
            : base("name=EcoSendEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblUserRole> tblUserRoles { get; set; }
        public virtual DbSet<tblUserToRole> tblUserToRoles { get; set; }
        public virtual DbSet<tblRecipient> tblRecipients { get; set; }
        public virtual DbSet<tblPack> tblPacks { get; set; }
        public virtual DbSet<tblUserMovement> tblUserMovements { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblParcel> tblParcels { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
    }
}
