//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoSendWeb.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public System.Guid pk_payment { get; set; }
        public System.Guid fk_user { get; set; }
        public int fk_parcel { get; set; }
        public decimal amount { get; set; }
        public bool success { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.DateTime> result_date { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblParcel tblParcel { get; set; }
    }
}
