//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoSendWeb.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParcel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblParcel()
        {
            this.tblPayments = new HashSet<tblPayment>();
            this.tblUserMovements = new HashSet<tblUserMovement>();
        }
    
        public int pk_parcel { get; set; }
        public int fk_pack { get; set; }
        public System.Guid fk_sender { get; set; }
        public System.Guid fk_recipient { get; set; }
        public decimal price { get; set; }
        public string destination_city { get; set; }
        public string destination_street { get; set; }
        public string destination_postal_code { get; set; }
        public string destination_country { get; set; }
        public Nullable<System.DateTime> confirmed_date { get; set; }
        public Nullable<System.Guid> fk_employee { get; set; }
        public System.DateTime created_date { get; set; }
        public bool is_pack_recycled { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
    
        public virtual tblPack tblPack { get; set; }
        public virtual tblRecipient tblRecipient { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayment> tblPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserMovement> tblUserMovements { get; set; }
    }
}
