//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoSendWeb.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserToRole
    {
        public System.Guid pk_map { get; set; }
        public System.Guid fk_user { get; set; }
        public int fk_role { get; set; }
    
        public virtual tblUserRole tblUserRole { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
